[tools]
"pipx:ansible-core" = "2.21.4"
age = "latest"
sops = "latest"
talhelper = "latest"
talosctl = "latest"
terraform = "latest"

[env]
SOPS_AGE_KEY_CMD = "op read op://homelab/age-keys/notesPlain"
